Resources:
  bbsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: regUser
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: N
      KeySchema:
        - AttributeName: type
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.bbsTableName}
      GlobalSecondaryIndexes:
        - IndexName: ${self:custom.bbsTypeGsi}
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE  
          Projection:
            ProjectionType: ALL
        - IndexName: ${self:custom.bbsRegUserGsi}
          KeySchema:
            - AttributeName: regUser
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE  
          Projection:
            ProjectionType: ALL
        - IndexName: ${self:custom.bbsCreatedAtGsi}
          KeySchema:
            - AttributeName: regUser
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        
        
