Resources:
  bodyValidator:
    Type: "AWS::ApiGateway::RequestValidator"
    Properties:
      Name: 'body-validator'
      RestApiId: 
        Ref: ApiGatewayRestApi
      ValidateRequestBody: true
      ValidateRequestParameters: false
  queryValidator:
    Type: "AWS::ApiGateway::RequestValidator"
    Properties:
      Name: 'query-validator'
      RestApiId: 
        Ref: ApiGatewayRestApi
      ValidateRequestBody: false
      ValidateRequestParameters: true

